meta_product_name: "My Orchestraa"
meta_title: "My Orchestraa - Music before anything else"
meta_description: "Orchestra planning and administration tool"
meta_image: "cover_landing.png"
twitter_account: "@product_twitter_account"
